[package]
name = "rv-mono"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rv-hir = { path = "../rv-hir" }
rv-hir-lower = { path = "../rv-hir-lower" }
rv-ty = { path = "../rv-ty" }
rv-mir = { path = "../rv-mir" }
rv-intern = { path = "../../foundation/rv-intern" }
rv-span = { path = "../../foundation/rv-span" }
rustc-hash.workspace = true
indexmap.workspace = true

[lints]
workspace = true
