[package]
name = "rv-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rv-span = { path = "../rv-span" }
rustc-hash.workspace = true
anyhow.workspace = true
