[package]
name = "rv-hir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rv-span = { path = "../../foundation/rv-span" }
rv-intern = { path = "../../foundation/rv-intern" }
rv-arena = { path = "../../foundation/rv-arena" }
serde.workspace = true
