[package]
name = "rv-database"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
salsa.workspace = true
rv-span = { path = "../rv-span" }
rv-vfs = { path = "../rv-vfs" }
rv-intern = { path = "../rv-intern" }
anyhow.workspace = true
